import type { Reference } from "./archivo-politico";
export type Dossier = {date:string; title:string; text:string; status:string; source:Reference; additionalSources?:Reference[]};
export const dossiers: Record<string,Dossier[]> = {
  marlaska: [{date:"2023-02-09",title:"Moción sobre la actuación del Gobierno en la frontera de Melilla",text:"El Congreso aprobó la moción del Grupo Popular relativa a la gestión del Gobierno tras los hechos del 24 de junio de 2022 en la frontera de Melilla, en los que fallecieron personas. El Diario de Sesiones recoge 173 votos a favor, 160 en contra y 15 abstenciones. La iniciativa cuestionaba la actuación del Ministerio del Interior durante su mandato.",status:"Decisión parlamentaria de control político. La aprobación de una moción no equivale a una condena judicial ni acredita responsabilidad penal personal.",source:{label:"Congreso · Diario de Sesiones, 9 de febrero de 2023, página 56",url:"https://www.congreso.es/public_oficiales/L14/CONG/DS/PL/DSCD-14-PL-242.PDF"}}],
  sanchez: [
    {date:"2018-06-01",title:"Acceso a la Presidencia tras la moción de censura",text:"El Congreso aprobó la moción de censura contra Mariano Rajoy y Pedro Sánchez accedió a la Presidencia. El cambio de Gobierno se recoge en el archivo de la XII legislatura y en el nombramiento publicado en el BOE.",status:"Decisión parlamentaria y nombramiento institucional; no es una evaluación de gestión.",source:{label:"La Moncloa · XII legislatura",url:"https://www.lamoncloa.gob.es/gobierno/gobiernosporlegislaturas/Paginas/xii-legislatura.aspx"}},
    {date:"2024-06-11",title:"Ley de amnistía durante su mandato",text:"Las Cortes aprobaron la Ley Orgánica 1/2024, relativa a actos vinculados al proceso independentista catalán. En 2025, la sentencia 137/2025 del Tribunal Constitucional descartó una prohibición constitucional general de las amnistías y declaró parcialmente inconstitucionales aspectos de su delimitación. La ley es una actuación legislativa de las Cortes, no una resolución personal del presidente.",status:"Referencia histórica: publicación de la ley y sentencia de 26 de junio de 2025. El texto consolidado recoge resoluciones posteriores; esta ficha no resume todos los procesos de aplicación.",source:{label:"BOE · Ley y evolución normativa",url:"https://www.boe.es/buscar/act.php?id=BOE-A-2024-11776"},additionalSources:[{label:"Tribunal Constitucional · Sentencia 137/2025",url:"https://boe.es/diario_boe/txt.php?id=BOE-A-2025-15939"}]},
  ],
  rajoy: [{date:"2018-06-01",title:"Moción de censura y cambio de Gobierno",text:"Su mandato terminó después de que el Congreso aprobara la moción de censura que dio paso a Pedro Sánchez. El archivo institucional permite consultar la composición del gabinete anterior y la del Gobierno posterior.",status:"Responsabilidad política parlamentaria. Este hecho no acredita por sí solo responsabilidad penal personal.",source:{label:"La Moncloa · Transición entre gabinetes en 2018",url:"https://www.lamoncloa.gob.es/gobierno/gobiernosporlegislaturas/Paginas/xii-legislatura.aspx"}}],
  robles: [{date:"2022-05-12",title:"Renovación de altos cargos de Defensa y del CNI",text:"Presidió la toma de posesión de Amparo Valcarce como secretaria de Estado de Defensa, Esperanza Casteleiro como directora del CNI y Adoración Mateos como subsecretaria. Casteleiro sustituyó a Paz Esteban al frente del CNI. La fuente documenta los relevos, sin establecer responsabilidades judiciales personales.",status:"Actuación institucional documentada; no constituye una investigación judicial ni una valoración sobre el motivo de los ceses.",source:{label:"Defensa · Toma de posesión de altos cargos",url:"https://www.defensa.gob.es/gabinete/notasPrensa/2022/05/DGC-20220512-toma-posesion-cargos.html"}}],
};
