// Explicaciones de propuestas hipotéticas: no describen por sí solas la ley vigente.
export type Context = { scope: string; considerations: [string, string] };
const bank: Record<string, [string, string, string][]> = {
  economia: [
    ["Se plantea que, durante una subida elevada y sostenida de precios, la Administración establezca un precio máximo temporal para determinados productos de primera necesidad, como algunos alimentos. No supone fijar todos los precios de la economía ni hacer permanente la medida. La pregunta no especifica qué productos, cuánto duraría ni cómo se compensaría a los proveedores.", "Puede dar prioridad a mantener asequibles los productos esenciales durante ese periodo.", "Puede dar prioridad a que los precios reflejen los costes y a evitar que un límite afecte al suministro."],
    ["Se compara la fijación de precios de la electricidad por empresas que compiten con una fijación administrativa. No se pregunta si debe existir una empresa pública, ni si deben darse ayudas a consumidores. La competencia puede coexistir con supervisión y normas del mercado.", "Puede dar prioridad a la competencia como mecanismo para ajustar precios y oferta.", "Puede dar prioridad a la intervención pública para estabilizar un servicio esencial."],
    ["Participar en la propiedad significa que el Estado posea una parte o la totalidad de ciertas empresas consideradas estratégicas. Energía e infraestructuras son ejemplos, no una lista cerrada. No se propone adquirir todas las empresas ni se fija el porcentaje de participación.", "Puede dar prioridad a que el Estado intervenga directamente en decisiones estratégicas.", "Puede dar prioridad a la gestión privada y a limitar el capital público comprometido."],
    ["La propuesta consiste en que el porcentaje de ingresos destinado a impuestos aumente cuando aumenta la renta. Pagar más euros con el mismo porcentaje es diferente de pagar una proporción mayor. No se plantea aquí un tipo impositivo ni un umbral concreto.", "Puede dar prioridad a repartir la contribución según la capacidad económica.", "Puede dar prioridad a mantener tipos más uniformes y a sus efectos sobre los incentivos."],
    ["Se plantea eliminar el impuesto que grava recibir una herencia, también en las herencias de mayor valor. No significa eliminar los demás impuestos sobre la propiedad o la renta. No se distingue aquí entre grados de parentesco ni entre comunidades autónomas.", "Puede dar prioridad a la transmisión del patrimonio familiar sin este gravamen.", "Puede dar prioridad a gravar la riqueza recibida y a la recaudación que permite."],
    ["Se propone aumentar el dinero destinado a prestaciones sociales y obtener más ingresos públicos para financiarlo. No se especifica la prestación ni el impuesto. La afirmación incluye ambas decisiones: más gasto y mayor recaudación.", "Puede dar prioridad a ampliar la protección social financiada colectivamente.", "Puede dar prioridad a contener la carga fiscal o a reasignar el gasto existente."],
  ],
  sociedad: [
    ["Se pregunta si la decisión de interrumpir un embarazo dentro de sus primeras 14 semanas debe corresponder a la mujer. El plazo es parte de la propuesta. No se pregunta por los supuestos posteriores, las condiciones clínicas concretas o la financiación del procedimiento.", "Puede dar prioridad a la autonomía de la mujer dentro del plazo señalado.", "Puede dar prioridad a establecer restricciones por la protección que atribuye a la gestación."],
    ["Se plantea que una persona adulta solicite voluntariamente asistencia médica para morir si tiene una enfermedad incurable, con comprobaciones médicas y legales. No se propone hacerlo sin consentimiento, ni equivale a retirar tratamientos o a recibir cuidados paliativos. Los controles concretos no se detallan.", "Puede dar prioridad a la decisión personal sobre el final de la vida.", "Puede dar prioridad a limitar esta práctica y a las garantías frente a presiones o errores."],
    ["La propuesta es mantener una prohibición del consumo personal de cannabis para mayores de edad. No se pregunta por menores, conducción, venta ni uso médico. Estar en desacuerdo con la prohibición no implica apoyar cualquier forma de comercialización.", "Puede dar prioridad a restringir el consumo por sus riesgos para la salud.", "Puede dar prioridad a la autonomía adulta y a otras formas de regulación."],
    ["Se plantea que centros públicos ofrezcan enseñanza religiosa voluntaria de distintas confesiones. No se propone que todo el alumnado deba asistir ni convertir una confesión en obligatoria. No se concreta cómo se financiarían o distribuirían las clases.", "Puede dar prioridad a facilitar opciones religiosas diversas dentro del centro.", "Puede dar prioridad a reservar esa enseñanza a espacios ajenos a los centros públicos."],
    ["Se pregunta por la igualdad de acceso a la adopción entre parejas del mismo sexo y las demás parejas. Las evaluaciones de idoneidad y protección del menor se mantienen para todas. La respuesta se refiere a la orientación sexual como criterio, no a eliminar requisitos de adopción.", "Puede dar prioridad a aplicar los mismos criterios de idoneidad a todas las parejas.", "Puede dar prioridad a otros criterios sobre el modelo familiar que considera adecuado."],
    ["Se plantea que una persona pueda solicitar atención administrativa en una lengua que sea cooficial en ese territorio. No se propone extender esa obligación a territorios donde no exista cooficialidad ni excluir la atención en castellano.", "Puede dar prioridad a garantizar la elección de lengua en esos servicios.", "Puede dar prioridad a un modelo común de atención y a sus necesidades organizativas."],
  ],
  trabajo: [
    ["Se propone aumentar la compensación económica por despido en contratos indefinidos. No se fija una cuantía ni se distinguen aquí todos los tipos de despido. No se pregunta por salarios, contratos temporales o prohibir los despidos.", "Puede dar prioridad a reforzar la protección económica ante la pérdida del empleo.", "Puede dar prioridad a la adaptación de las plantillas y al coste de contratar."],
    ["Se propone ampliar las situaciones en que una empresa puede contratar por un periodo limitado. No se propone suprimir todos los contratos indefinidos ni cambiar el salario. Las causas y límites concretos de temporalidad no se definen.", "Puede dar prioridad a la flexibilidad para responder a necesidades cambiantes.", "Puede dar prioridad a la estabilidad del empleo y a limitar la contratación temporal."],
    ["La propuesta reduce el máximo de horas de trabajo manteniendo el salario mensual. No se refiere a reducir también el sueldo ni solo a repartir las mismas horas en menos días. No se fija el nuevo máximo ni las reglas para sectores concretos.", "Puede dar prioridad al tiempo disponible y a una menor duración del trabajo.", "Puede dar prioridad a los costes, la productividad y la organización de cada actividad."],
    ["Un convenio sectorial es un acuerdo colectivo sobre condiciones de trabajo para un sector. Se plantea que sus mínimos se apliquen a todas sus empresas, que podrían mejorarlos. No se plantea que todas tengan condiciones idénticas por encima de esos mínimos.", "Puede dar prioridad a una protección común negociada para el sector.", "Puede dar prioridad a adaptar más condiciones a la situación de cada empresa."],
    ["La palabra exclusivamente significa que el salario se acordaría entre cada persona y su empresa, sin que un convenio colectivo determinase ese salario. No se especifica aquí si existiría un salario mínimo legal. Se compara el papel del pacto individual con el colectivo.", "Puede dar prioridad al acuerdo individual y a su adaptación a cada relación laboral.", "Puede dar prioridad al poder negociador y a los mínimos de los acuerdos colectivos."],
    ["Se plantea que la representación de los trabajadores intervenga en decisiones sobre reorganizaciones de personal, mediante información, consulta o negociación. No se atribuye automáticamente un veto ni se fija el mecanismo. No se pregunta por todas las decisiones empresariales.", "Puede dar prioridad a incluir la voz de la plantilla en esos procesos.", "Puede dar prioridad a la autonomía y rapidez de las decisiones de gestión."],
  ],
  servicios: [
    ["Se distingue financiación pública de gestión pública. Un servicio puede pagarse con fondos públicos y prestarse en un centro privado. La propuesta favorece que la mayoría de la atención financiada públicamente se gestione en centros públicos, sin excluir toda colaboración privada.", "Puede dar prioridad a la gestión directa y al control público del servicio.", "Puede dar prioridad a combinar proveedores según capacidad, coste y acceso."],
    ["Se propone que fondos públicos destinados a la educación puedan utilizarse en el centro privado elegido por la familia. No se define la cantidad, el sistema de admisión ni los requisitos del centro. La pregunta se refiere al destino de la financiación.", "Puede dar prioridad a ampliar la elección de centro con financiación pública.", "Puede dar prioridad a concentrar esos recursos en la red pública."],
    ["Se pregunta quién gestiona principalmente las residencias financiadas con recursos públicos. La propuesta favorece la gestión directa pública. No modifica por sí sola los requisitos para acceder ni exige que todas las residencias sean públicas.", "Puede dar prioridad al control directo de la gestión y los cuidados.", "Puede dar prioridad a la diversidad de proveedores y a su capacidad de prestación."],
    ["Se plantea una oferta de educación de cero a tres años sin pago para las familias y financiada públicamente, con independencia de su renta. No se propone obligar a escolarizar ni se detalla cómo se organizarían las plazas.", "Puede dar prioridad al acceso común y a facilitar la conciliación.", "Puede dar prioridad a focalizar ayudas o a otros usos de los recursos."],
    ["La propuesta condiciona las ayudas de cuidados de larga duración a disponer de pocos recursos. Se compara una ayuda según renta con un acceso que no dependa de ella. No se plantea retirar todos los servicios de cuidados ni se fija el umbral económico.", "Puede dar prioridad a destinar ayudas a quienes tienen menor capacidad de pago.", "Puede dar prioridad a un acceso común basado en la necesidad de cuidados."],
    ["Se plantea incluir atención dental básica en la cobertura sanitaria pública para toda la población. No se incluyen tratamientos solo estéticos ni se concreta un catálogo de prestaciones. La financiación y la capacidad asistencial forman parte de su aplicación.", "Puede dar prioridad a ampliar la cobertura y reducir barreras económicas.", "Puede dar prioridad a otras prestaciones sanitarias o a una cobertura más focalizada."],
  ],
  vivienda: [
    ["Se propone un precio máximo legal de alquiler en zonas con mucha demanda. No se establece aquí el límite, el tipo de contrato o la duración de la medida. No se pregunta por ayudas al alquiler ni por construir vivienda pública.", "Puede dar prioridad a limitar el precio que pagan los inquilinos.", "Puede dar prioridad a la oferta disponible y a la libertad de pactar el precio."],
    ["Se propone permitir el uso turístico de una vivienda sin una autorización especial para ese uso. Seguirían existiendo las obligaciones fiscales y de seguridad generales. No se propone eliminar toda regulación ni se concreta el efecto de las normas de la comunidad de propietarios.", "Puede dar prioridad a la libertad de uso de la propiedad.", "Puede dar prioridad a controlar ese uso por sus efectos sobre vivienda y entorno."],
    ["Se plantea un impuesto adicional sobre viviendas habitables que lleven mucho tiempo vacías. Se excluyen obras y causas justificadas. No se define la duración necesaria ni el recargo, y no se propone expropiar la vivienda.", "Puede dar prioridad a incentivar que las viviendas se utilicen.", "Puede dar prioridad a limitar la carga fiscal y a valorar los motivos de desocupación."],
    ["Se propone priorizar nuevas viviendas en zonas ya urbanizadas antes de extender la ciudad. Puede implicar rehabilitación, aprovechamiento de parcelas o mayor densidad. No se exige prohibir todos los nuevos barrios periféricos.", "Puede dar prioridad a aprovechar infraestructuras y suelo existentes.", "Puede dar prioridad a otras necesidades de espacio, densidad y disponibilidad de suelo."],
    ["Se plantea habilitar más suelo residencial en los bordes de las ciudades para construir viviendas. No se define una localización ni se elimina la necesidad de infraestructuras. Se pregunta por la expansión como política general.", "Puede dar prioridad a ampliar el suelo y las posibilidades de construcción.", "Puede dar prioridad a contener la extensión urbana y a los costes de servicios y movilidad."],
    ["Se propone situar nuevos desarrollos de viviendas y servicios cerca del transporte público. No significa eliminar otras formas de movilidad ni trasladar obligatoriamente a quienes ya viven en otros lugares.", "Puede dar prioridad a la proximidad y al acceso mediante transporte colectivo.", "Puede dar prioridad a otros criterios de distribución y a la diversidad de ubicaciones."],
  ],
  medioambiente: [
    ["Se plantea adelantar el ritmo de reducción de emisiones aceptando mayores costes inmediatos. No se fija un calendario ni una tecnología. La pregunta incluye expresamente el intercambio entre rapidez y costes a corto plazo.", "Puede dar prioridad a una reducción más rápida de las emisiones.", "Puede dar prioridad a una adaptación gradual y al reparto de los costes."],
    ["Se propone retrasar restricciones a vehículos contaminantes hasta que todos los hogares dispongan de alternativas asequibles. No se pregunta por suprimir las restricciones definitivamente ni se define qué alternativa sería suficiente.", "Puede dar prioridad a la capacidad de adaptación de todos los hogares.", "Puede dar prioridad a aplicar antes las restricciones por sus objetivos ambientales."],
    ["Se plantea dar preferencia a las renovables al asignar subvenciones públicas, frente a subvencionar combustibles fósiles. No equivale a prohibir esos combustibles ni a decidir aquí sobre energía nuclear.", "Puede dar prioridad a orientar las ayudas hacia fuentes renovables.", "Puede dar prioridad a otros criterios de coste, suministro o transición."],
    ["Se compara la protección de un espacio natural protegido con autorizar nuevos proyectos productivos que lo afecten. No se afirma que cualquier actividad económica produzca el mismo impacto ni se plantea proteger todo el territorio por igual.", "Puede dar prioridad a mantener la protección del espacio afectado.", "Puede dar prioridad a permitir determinados proyectos según sus beneficios y condiciones."],
    ["Se plantea ampliar el regadío aceptando una disminución del caudal de los ríos. No se determina cuánto disminuiría ni se propone eliminar los ríos o todas sus protecciones. La reducción de caudal forma parte de la situación que se valora.", "Puede dar prioridad a ampliar la producción agrícola mediante riego.", "Puede dar prioridad a mantener los caudales y sus usos y funciones ambientales."],
    ["Se propone limitar actividades económicas cuando exista un impacto demostrado que comprometa una especie amenazada. No se plantea limitar cualquier actividad sin evaluar sus efectos, ni se define la intensidad de la limitación.", "Puede dar prioridad a evitar daños a la conservación de la especie.", "Puede dar prioridad a buscar otras medidas compatibles con la actividad económica."],
  ],
  exterior: [
    ["Se plantea que más decisiones económicas correspondan a instituciones de la Unión Europea y menos exclusivamente a cada Estado. No se pregunta por una medida fiscal particular ni por abandonar la UE.", "Puede dar prioridad a coordinar decisiones económicas entre países.", "Puede dar prioridad a la autonomía de cada Estado para decidir."],
    ["Se plantea decidir la política migratoria española sin compromisos obligatorios acordados con otros países europeos. No implica dejar de dialogar con ellos ni determina si la política resultante sería más abierta o más restrictiva.", "Puede dar prioridad a la capacidad nacional de decisión.", "Puede dar prioridad a compartir compromisos y responsabilidades entre países."],
    ["Se propone que los países que acepten acuerdos climáticos tengan obligación de cumplirlos. No se propone imponer un acuerdo a países que no lo hayan suscrito ni se define la sanción por incumplimiento.", "Puede dar prioridad a la exigibilidad de los compromisos compartidos.", "Puede dar prioridad a la flexibilidad nacional para aplicar o revisar esos compromisos."],
    ["Se plantea aumentar el dinero público destinado a defensa. No se fija un porcentaje, el material a adquirir ni una operación militar. No equivale por sí solo a apoyar una guerra o intervención.", "Puede dar prioridad a ampliar los recursos y capacidades de defensa.", "Puede dar prioridad a contener ese gasto o a destinar recursos a otras políticas."],
    ["Se propone trasladar una parte del gasto militar a cooperación internacional. Esto implica reducir un destino de gasto para aumentar el otro. No se define la cantidad ni un programa concreto de cooperación.", "Puede dar prioridad a aumentar los recursos para cooperación.", "Puede dar prioridad a conservar esos recursos en capacidades militares."],
    ["Se plantea aportar más financiación a capacidades militares desarrolladas o utilizadas en común con aliados. No se pregunta por una intervención concreta ni se establece qué alianza o proyecto recibiría fondos.", "Puede dar prioridad a compartir recursos y capacidades con aliados.", "Puede dar prioridad a otras formas de defensa o al control nacional del gasto."],
  ],
  instituciones: [
    ["Se plantea consultar directamente a la ciudadanía mediante referéndum sobre decisiones de especial relevancia. No se define cuáles ni se eliminan las garantías del procedimiento. No se propone que todas las decisiones deban votarse directamente.", "Puede dar prioridad a la decisión directa de la ciudadanía en esas materias.", "Puede dar prioridad a la deliberación y responsabilidad de los representantes."],
    ["Se propone que las decisiones legislativas correspondan solo a representantes elegidos, excluyendo decisiones ciudadanas directas sobre leyes. No se excluyen por ello la opinión pública, las peticiones o la participación en otros procesos.", "Puede dar prioridad a la representación parlamentaria y sus procedimientos.", "Puede dar prioridad a complementar la representación con decisiones directas."],
    ["Se plantea que reunir suficientes firmas permita promover una consulta cuyo resultado obligue a actuar. No se fija el número de firmas, las materias admitidas o las garantías. Una consulta vinculante es diferente de una mera petición.", "Puede dar prioridad a facilitar una iniciativa ciudadana con efecto decisorio.", "Puede dar prioridad a las garantías, los límites y el papel de las instituciones representativas."],
    ["Se propone ampliar la capacidad de las comunidades autónomas para decidir sobre impuestos. No se define qué tributos ni se propone automáticamente aumentar o reducir la presión fiscal. Se pregunta por quién decide.", "Puede dar prioridad a adaptar la política fiscal a cada territorio.", "Puede dar prioridad a la coordinación, la igualdad territorial y las decisiones estatales."],
    ["Se propone concentrar decisiones educativas en el Gobierno central frente a distribuirlas territorialmente. No se pregunta por el contenido de una asignatura ni por la gestión de un centro concreto.", "Puede dar prioridad a un marco de decisiones común para todo el Estado.", "Puede dar prioridad a la capacidad de adaptar las decisiones a cada territorio."],
    ["Se plantea que los municipios tengan más capacidad para decidir cómo gestionan sus recursos. No se fija un aumento de ingresos ni se eliminan los controles de legalidad. Se pregunta por el margen de decisión local.", "Puede dar prioridad a las decisiones cercanas a las necesidades municipales.", "Puede dar prioridad a la coordinación y a reglas comunes entre administraciones."],
  ],
};
export const contexts: Record<string, Context> = Object.fromEntries(
  Object.entries(bank).flatMap(([category, rows]) => rows.map(([scope, a, b], i) => [
    `${category}-${i + 1}`, { scope, considerations: [a, b] },
  ])),
);
